format = """
[ğŸ­¨](fg:primary)\
[ó°£‡ ](bg:primary fg:on_primary)\
[ğŸ­¬](bg:secondary fg:primary)\
$directory\
[ğŸ­¬](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[ğŸ­¬](fg:tertiary)\
$character
"""

palette = 'colors'

[palettes.colors]
primary = '#a0cafd'
on_primary = '#003258'
secondary = '#bbc7db'
on_secondary = '#253140'
tertiary = '#d6bee4'
on_tertiary = '#3b2948'

[character]
success_symbol = '[â¯](fg:primary)'
error_symbol = '[â¯](fg:primary)'

[directory]
style = "fg:on_secondary bg:secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on_tertiary bg:tertiary)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind )](fg:on_tertiary bg:tertiary)]($style)'
