# : Manager [[[

[manager]
cwd = { fg = "#dee4df" }

# Tab
tab_active = { fg = "#003829", bg = "#8ad6b8", bold = true }
tab_inactive = { fg = "#a5f2d3", bg = "#002117" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5fc3fa", bg = "#5fc3fa" }
marker_cut = { fg = "#c2e8fd", bg = "#c2e8fd" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a7cce0", bg = "#a7cce0" }

# Count
count_copied = { fg = "#001e2b", bg = "#c2e8fd" }
count_cut = { fg = "#001e2b", bg = "#c2e8fd" }
count_selected = { fg = "#003829", bg = "#a7cce0" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#8ad6b8" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003829", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#8ad6b8", fg = "#003829", bold = true }
normal_alt  = { bg = "#404944", fg = "#bfc9c3" }

# Select mode
select_main = { bg = "#b3ccc0", fg = "#1e352c", bold = true }
select_alt  = { bg = "#404944", fg = "#bfc9c3" }

# Unset mode
unset_main = { bg = "#a7cce0", fg = "#0a3445", bold = true }
unset_alt  = { bg = "#404944", fg = "#bfc9c3" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8ad6b8", bg = "#343b37" }
progress_error = { fg = "#ffb4ab", bg = "#343b37" }

# Permissions
permissions_t = { fg = "#5c8a74" }
permissions_w = { fg = "#3e88b0" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#2eb0f8" }
permissions_s = { fg = "#20de91" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#8ad6b8" }
active = { fg = "#a7cce0", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#8ad6b8" }
value = { fg = "#dee4df" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#8ad6b8", bg = "#003829" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#8ad6b8" }
title = {}
hovered = { fg = "#c2e8fd", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343b37" }
cand = { fg = "#8ad6b8" }
rest = { fg = "#003829" }
desc = { fg = "#dee4df" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee4df" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee4df" }
run = { fg = "#dee4df" }
footer = { fg = "#1e352c", bg = "#b3ccc0" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a7cce0" }
title_warn = { fg = "#8ad6b8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee4df" },
    { name = "*/", fg = "#8ad6b8" },
]

# : ]]]
